GET http://localhost:8080/todo HTTP/2

###

POST http://localhost:8080/todo HTTP/2
Content-Type: application/json

{
  "title": "Go for a run",
  "description": "Run for at least 30 minutes.",
  "priority": 3
}

###

DELETE http://localhost:8080/todo/1 HTTP/2

###

PATCH http://localhost:8080/todo/0 HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "title": "Yippee",
  "description": "YipYip",
  "priority": "2"
}
